# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-01 19:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accountid", models.IntegerField(unique=True)),
                ("timerank", models.IntegerField()),
                ("aliases", models.CharField(max_length=2048)),
                ("country", models.CharField(max_length=2)),
                ("game_pref", models.SmallIntegerField(default=0)),
                ("game_pref_fixed", models.BooleanField(default=False)),
                ("is_developer", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("user__username",),},
        ),
    ]
