# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srs", "0002_auto_20161105_1230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playeraccount",
            name="accountid",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="replay",
            name="gameID",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="sldbmatchskillscache",
            name="gameID",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
