# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0003_auto_20161107_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursedAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air', models.PositiveIntegerField(default=0, verbose_name=b'Airforce General')),
                ('bug', models.PositiveIntegerField(default=0, verbose_name=b'Bug Hunter')),
                ('cap', models.PositiveIntegerField(default=0, verbose_name=b'Mind Magician')),
                ('dran', models.PositiveIntegerField(default=0, verbose_name=b'Dragons & Angels')),
                ('drankill', models.PositiveIntegerField(default=0, verbose_name=b'Dragon & Angel Slayer')),
                ('emp', models.PositiveIntegerField(default=0, verbose_name=b'Stun Wizard')),
                ('fire', models.PositiveIntegerField(default=0, verbose_name=b'Master Grill-Chef')),
                ('friend', models.PositiveIntegerField(default=0, verbose_name=b'Friendly Fire Award')),
                ('heart', models.PositiveIntegerField(default=0, verbose_name=b'Queen Heart Breaker')),
                ('hero', models.PositiveIntegerField(default=0, verbose_name=b'Heros do the job')),
                ('herokill', models.PositiveIntegerField(default=0, verbose_name=b'Hero Hunter')),
                ('hover', models.PositiveIntegerField(default=0, verbose_name=b'Hover Admiral')),
                ('kam', models.PositiveIntegerField(default=0, verbose_name=b'Kamikaze Award')),
                ('lycan', models.PositiveIntegerField(default=0, verbose_name=b'Werewolf Hunter')),
                ('mex', models.PositiveIntegerField(default=0, verbose_name=b'Mineral Prospector')),
                ('mexkill', models.PositiveIntegerField(default=0, verbose_name=b'Loot & Pillage')),
                ('nux', models.PositiveIntegerField(default=0, verbose_name=b'Apocalyptic Achievement Award')),
                ('ouch', models.PositiveIntegerField(default=0, verbose_name=b'Big Purple Heart')),
                ('point', models.PositiveIntegerField(default=0, verbose_name=b'This is my Land')),
                ('pwn', models.PositiveIntegerField(default=0, verbose_name=b'Total Pain')),
                ('rezz', models.PositiveIntegerField(default=0, verbose_name=b'Vile Necromancer')),
                ('share', models.PositiveIntegerField(default=0, verbose_name=b'Share Bear')),
                ('shell', models.PositiveIntegerField(default=0, verbose_name=b'Turtle Shell')),
                ('slow', models.PositiveIntegerField(default=0, verbose_name=b'Traffic Cop')),
                ('sweeper', models.PositiveIntegerField(default=0, verbose_name=b'Land Sweeper')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srs.Player')),
                ('replay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srs.Replay')),
            ],
        ),
    ]
