# Generated by Django 3.0.2 on 2020-01-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0007_teamstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrareplaymedia',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='extrareplaymedia',
            name='media',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mapimg',
            name='startpostype',
            field=models.IntegerField(blank=True, null=True, verbose_name='-1 means full image'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='match_type',
            field=models.CharField(choices=[('1', '1v1'), ('T', 'Team'), ('F', 'FFA'), ('G', 'TeamFFA'), ('L', 'Global')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='ratinghistory',
            name='match_type',
            field=models.CharField(choices=[('1', '1v1'), ('T', 'Team'), ('F', 'FFA'), ('G', 'TeamFFA'), ('L', 'Global')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='replay',
            name='unixTime',
            field=models.DateTimeField(db_index=True, verbose_name='date of match'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='versionString',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='replay',
            name='wallclockTime',
            field=models.CharField(max_length=32, verbose_name='length of match'),
        ),
        migrations.AlterField(
            model_name='sldbleaderboardgame',
            name='match_type',
            field=models.CharField(choices=[('1', '1v1'), ('T', 'Team'), ('F', 'FFA'), ('G', 'TeamFFA'), ('L', 'Global')], db_index=True, max_length=1),
        ),
    ]
