# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 00:00
from __future__ import unicode_literals

from django.db import migrations

import srs.models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0007_teamstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='metadata2',
            field=srs.models.JSONTextField(blank=True, default=None, null=True),
        ),
    ]
