# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 13:44
from __future__ import unicode_literals

from django.db import migrations

import srs.models


class Migration(migrations.Migration):

    dependencies = [
        ("srs", "0009_remove_map_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitestats",
            name="all_players",
            field=srs.models.JSONTextField(),
        ),
        migrations.AlterField(
            model_name="sitestats", name="bawards", field=srs.models.JSONTextField(),
        ),
    ]
