# Generated by Django 3.0.2 on 2020-01-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0008_auto_20200120_0325'),
        ('srs', '0010_auto_20200127_1444'),
    ]

    operations = [
    ]
